use std::{
    error::Error,
    fmt,
    str::FromStr,
    time::{SystemTime, SystemTimeError, UNIX_EPOCH},
};

use uuid::{Uuid, Variant, Version};

/// A stable, opaque identifier for a Tule project.
///
/// New identifiers are UUID version 7 values generated by the core. Parsing
/// also requires version 7 so persisted identifiers cannot silently cross the
/// project identity boundary with another UUID version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ProjectId(Uuid);

impl ProjectId {
    /// Generates a new UUID version 7 project identifier.
    #[must_use]
    pub fn generate() -> Self {
        Self(Uuid::now_v7())
    }

    /// Parses a persisted UUID version 7 project identifier.
    pub fn parse(value: &str) -> Result<Self, InvalidProjectId> {
        value.parse()
    }
}

impl fmt::Display for ProjectId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl FromStr for ProjectId {
    type Err = InvalidProjectId;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let id = Uuid::parse_str(value).map_err(|_| InvalidProjectId::Malformed)?;
        if id.get_variant() != Variant::RFC4122 {
            return Err(InvalidProjectId::InvalidVariant);
        }
        if id.get_version() != Some(Version::SortRand) {
            return Err(InvalidProjectId::NotVersionSeven);
        }

        Ok(Self(id))
    }
}

/// The reason a persisted project identifier is invalid.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvalidProjectId {
    /// The value is not a UUID.
    Malformed,
    /// The UUID does not use the RFC 4122 variant specified by RFC 9562.
    InvalidVariant,
    /// The value is a UUID, but not UUID version 7.
    NotVersionSeven,
}

impl fmt::Display for InvalidProjectId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Malformed => formatter.write_str("project ID is not a valid UUID"),
            Self::InvalidVariant => {
                formatter.write_str("project ID does not use the RFC 4122 UUID variant")
            }
            Self::NotVersionSeven => formatter.write_str("project ID is not UUID version 7"),
        }
    }
}

impl Error for InvalidProjectId {}

/// A validated, normalized project name.
///
/// Surrounding Unicode whitespace is removed during construction. The stored
/// value contains between 1 and 100 Unicode scalar values and no control
/// characters. Names are labels rather than unique keys, so duplicate names
/// are valid.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ProjectName(String);

impl ProjectName {
    /// The largest accepted project name in Unicode scalar values.
    pub const MAX_SCALARS: usize = 100;

    /// Validates and normalizes a project name.
    pub fn new(value: impl AsRef<str>) -> Result<Self, InvalidProjectName> {
        let trimmed = value.as_ref().trim();
        let scalar_count = trimmed.chars().count();

        if scalar_count == 0 {
            return Err(InvalidProjectName::Empty);
        }
        if scalar_count > Self::MAX_SCALARS {
            return Err(InvalidProjectName::TooLong { scalar_count });
        }
        if trimmed.chars().any(char::is_control) {
            return Err(InvalidProjectName::ContainsControlCharacter);
        }

        Ok(Self(trimmed.to_owned()))
    }

    /// Returns the normalized project name.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ProjectName {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(formatter)
    }
}

impl TryFrom<&str> for ProjectName {
    type Error = InvalidProjectName;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

impl TryFrom<String> for ProjectName {
    type Error = InvalidProjectName;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::new(value)
    }
}

/// The reason a project name is invalid.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvalidProjectName {
    /// No Unicode scalar values remain after trimming surrounding whitespace.
    Empty,
    /// The normalized name is longer than [`ProjectName::MAX_SCALARS`].
    TooLong {
        /// The number of Unicode scalar values in the normalized input.
        scalar_count: usize,
    },
    /// The normalized name contains a Unicode control character.
    ContainsControlCharacter,
}

impl fmt::Display for InvalidProjectName {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => formatter.write_str("project name is empty"),
            Self::TooLong { scalar_count } => write!(
                formatter,
                "project name has {scalar_count} Unicode scalar values; the maximum is {}",
                ProjectName::MAX_SCALARS
            ),
            Self::ContainsControlCharacter => {
                formatter.write_str("project name contains a control character")
            }
        }
    }
}

impl Error for InvalidProjectName {}

/// A Tule project as represented by the framework-independent core.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Project {
    id: ProjectId,
    name: ProjectName,
    instructions: String,
    created_at_unix_ms: i64,
}

impl Project {
    /// Creates a project with a core-generated identifier and current Unix time.
    pub fn create(name: ProjectName) -> Result<Self, ProjectTimeError> {
        Ok(Self {
            id: ProjectId::generate(),
            name,
            instructions: String::new(),
            created_at_unix_ms: current_unix_milliseconds()?,
        })
    }

    /// Reconstructs a project from storage-neutral persisted values.
    ///
    /// This constructor deliberately accepts ordinary Rust values so a storage
    /// adapter can validate records without exposing SQLite or Tauri types to
    /// the core.
    pub fn from_stored_parts(
        id: &str,
        name: &str,
        instructions: &str,
        created_at_unix_ms: i64,
    ) -> Result<Self, ProjectReconstructionError> {
        let id = ProjectId::parse(id).map_err(ProjectReconstructionError::InvalidId)?;
        let name = ProjectName::new(name).map_err(ProjectReconstructionError::InvalidName)?;

        Ok(Self {
            id,
            name,
            instructions: instructions.to_owned(),
            created_at_unix_ms,
        })
    }

    /// Returns the project's stable identifier.
    #[must_use]
    pub fn id(&self) -> ProjectId {
        self.id
    }

    /// Returns the project's validated name.
    #[must_use]
    pub fn name(&self) -> &ProjectName {
        &self.name
    }

    /// Returns the project's instructions exactly as supplied.
    ///
    /// Instructions are plain Unicode text. The core does not trim, normalize,
    /// validate, or interpret their contents.
    #[must_use]
    pub fn instructions(&self) -> &str {
        &self.instructions
    }

    /// Returns creation time as milliseconds since the Unix epoch.
    #[must_use]
    pub fn created_at_unix_ms(&self) -> i64 {
        self.created_at_unix_ms
    }
}

/// A failure to read the current time as signed 64-bit Unix milliseconds.
#[derive(Debug)]
pub enum ProjectTimeError {
    /// The system clock reports a time before the Unix epoch.
    BeforeUnixEpoch(SystemTimeError),
    /// The current time cannot fit in a signed 64-bit millisecond value.
    OutOfRange,
}

impl fmt::Display for ProjectTimeError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::BeforeUnixEpoch(_) => {
                formatter.write_str("system clock is before the Unix epoch")
            }
            Self::OutOfRange => {
                formatter.write_str("current Unix time does not fit in signed 64-bit milliseconds")
            }
        }
    }
}

impl Error for ProjectTimeError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::BeforeUnixEpoch(error) => Some(error),
            Self::OutOfRange => None,
        }
    }
}

/// The reason persisted project values cannot reconstruct a [`Project`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectReconstructionError {
    /// The persisted project identifier is invalid.
    InvalidId(InvalidProjectId),
    /// The persisted project name is invalid.
    InvalidName(InvalidProjectName),
}

impl fmt::Display for ProjectReconstructionError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidId(error) => write!(formatter, "invalid persisted project ID: {error}"),
            Self::InvalidName(error) => {
                write!(formatter, "invalid persisted project name: {error}")
            }
        }
    }
}

impl Error for ProjectReconstructionError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::InvalidId(error) => Some(error),
            Self::InvalidName(error) => Some(error),
        }
    }
}

fn current_unix_milliseconds() -> Result<i64, ProjectTimeError> {
    let duration = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(ProjectTimeError::BeforeUnixEpoch)?;
    i64::try_from(duration.as_millis()).map_err(|_| ProjectTimeError::OutOfRange)
}

#[cfg(test)]
mod tests {
    use std::{
        convert::Infallible,
        sync::atomic::{AtomicUsize, Ordering},
    };

    use crate::{OpenProjectError, ProjectRepository, open_project};

    use super::*;

    const WRONG_VARIANT_VERSION_SEVEN_ID: &str = "01890f47-64b0-7cc1-18e8-bb5d4a3b1234";

    #[derive(Default)]
    struct LookupCountingRepository {
        lookup_count: AtomicUsize,
    }

    impl ProjectRepository for LookupCountingRepository {
        type Error = Infallible;

        fn create(&self, _project: &Project) -> Result<(), Self::Error> {
            Ok(())
        }

        fn list(&self) -> Result<Vec<Project>, Self::Error> {
            Ok(Vec::new())
        }

        fn find_by_id(&self, _id: &ProjectId) -> Result<Option<Project>, Self::Error> {
            self.lookup_count.fetch_add(1, Ordering::Relaxed);
            Ok(None)
        }

        fn update_instructions(
            &self,
            _id: &ProjectId,
            _instructions: &str,
        ) -> Result<Option<Project>, Self::Error> {
            Ok(None)
        }
    }

    #[test]
    fn generated_ids_are_version_seven_and_round_trip() {
        let id = ProjectId::generate();
        let persisted = id.to_string();
        let parsed = Uuid::parse_str(&persisted).unwrap();

        assert_eq!(parsed.get_version_num(), 7);
        assert_eq!(parsed.get_variant(), Variant::RFC4122);
        assert_eq!(ProjectId::parse(&persisted), Ok(id));
    }

    #[test]
    fn malformed_and_non_version_seven_ids_are_typed() {
        assert_eq!(
            ProjectId::parse("not-a-uuid"),
            Err(InvalidProjectId::Malformed)
        );
        assert_eq!(
            ProjectId::parse("550e8400-e29b-41d4-a716-446655440000"),
            Err(InvalidProjectId::NotVersionSeven)
        );
    }

    #[test]
    fn wrong_variant_version_seven_ids_short_circuit_open_before_repository_access() {
        let repository = LookupCountingRepository::default();

        assert_eq!(
            ProjectId::parse(WRONG_VARIANT_VERSION_SEVEN_ID),
            Err(InvalidProjectId::InvalidVariant)
        );
        assert!(matches!(
            open_project(&repository, WRONG_VARIANT_VERSION_SEVEN_ID),
            Err(OpenProjectError::InvalidId(
                InvalidProjectId::InvalidVariant
            ))
        ));
        assert_eq!(repository.lookup_count.load(Ordering::Relaxed), 0);
    }

    #[test]
    fn project_names_are_trimmed() {
        let name = ProjectName::new("  Tule project  ").unwrap();

        assert_eq!(name.as_str(), "Tule project");
    }

    #[test]
    fn project_name_boundaries_count_unicode_scalar_values() {
        let one_scalar = ProjectName::new("é").unwrap();
        let one_hundred_scalars = ProjectName::new("🙂".repeat(100)).unwrap();

        assert_eq!(one_scalar.as_str().chars().count(), 1);
        assert_eq!(one_hundred_scalars.as_str().chars().count(), 100);
        assert_eq!(ProjectName::new("  "), Err(InvalidProjectName::Empty));
        assert_eq!(
            ProjectName::new("🙂".repeat(101)),
            Err(InvalidProjectName::TooLong { scalar_count: 101 })
        );
    }

    #[test]
    fn normalized_project_names_reject_control_characters() {
        assert_eq!(
            ProjectName::new("alpha\u{0000}beta"),
            Err(InvalidProjectName::ContainsControlCharacter)
        );
        assert_eq!(ProjectName::new("\n alpha \r").unwrap().as_str(), "alpha");
    }

    #[test]
    fn stored_projects_are_reconstructed_without_storage_types() {
        let id = ProjectId::generate();
        let instructions = "  Keep exact spacing\r\nCafe\u{301} 🙂  ";
        let project =
            Project::from_stored_parts(&id.to_string(), "  Saved  ", instructions, 1_234).unwrap();

        assert_eq!(project.id(), id);
        assert_eq!(project.name().as_str(), "Saved");
        assert_eq!(project.instructions(), instructions);
        assert_eq!(project.created_at_unix_ms(), 1_234);
    }

    #[test]
    fn newly_created_projects_have_empty_instructions() {
        let project = Project::create(ProjectName::new("New project").unwrap()).unwrap();

        assert_eq!(project.instructions(), "");
    }

    #[test]
    fn reconstruction_reports_invalid_identifiers_and_names() {
        assert_eq!(
            Project::from_stored_parts("bad", "Valid", "", 0),
            Err(ProjectReconstructionError::InvalidId(
                InvalidProjectId::Malformed
            ))
        );

        let id = ProjectId::generate();
        assert_eq!(
            Project::from_stored_parts(&id.to_string(), "", "", 0),
            Err(ProjectReconstructionError::InvalidName(
                InvalidProjectName::Empty
            ))
        );
    }
}
